#!/bin/bash

API_KEY="sk_S3ZrDip07cbRdr52ceSmdX_ZJx7ni8j0SBoNoWsgxnQ="
BASE_URL="http://localhost:8000/api"

echo "Creating HTTP Routers..."
curl -X POST "$BASE_URL/http/routers" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Router0","config":{"entryPoints":["foobar","foobar"],"middlewares":["foobar","foobar"],"service":"foobar","rule":"foobar","parentRefs":["foobar","foobar"],"ruleSyntax":"foobar","priority":42,"tls":{"options":"foobar","certResolver":"foobar","domains":[{"main":"foobar","sans":["foobar","foobar"]},{"main":"foobar","sans":["foobar","foobar"]}]},"observability":{"accessLogs":true,"metrics":true,"tracing":true,"traceVerbosity":"foobar"}}}'
curl -X POST "$BASE_URL/http/routers" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Router1","config":{"entryPoints":["foobar","foobar"],"middlewares":["foobar","foobar"],"service":"foobar","rule":"foobar","parentRefs":["foobar","foobar"],"ruleSyntax":"foobar","priority":42,"tls":{"options":"foobar","certResolver":"foobar","domains":[{"main":"foobar","sans":["foobar","foobar"]},{"main":"foobar","sans":["foobar","foobar"]}]},"observability":{"accessLogs":true,"metrics":true,"tracing":true,"traceVerbosity":"foobar"}}}'

echo "Creating HTTP Services..."
curl -X POST "$BASE_URL/http/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Service01","config":{"failover":{"service":"foobar","fallback":"foobar","healthCheck":{}}}}'
curl -X POST "$BASE_URL/http/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Service02","config":{"highestRandomWeight":{"services":[{"name":"foobar","weight":42},{"name":"foobar","weight":42}],"healthCheck":{}}}}'
curl -X POST "$BASE_URL/http/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Service03","config":{"loadBalancer":{"sticky":{"cookie":{"name":"foobar","secure":true,"httpOnly":true,"sameSite":"foobar","maxAge":42,"path":"foobar","domain":"foobar"}},"servers":[{"url":"foobar","weight":42,"preservePath":true},{"url":"foobar","weight":42,"preservePath":true}],"strategy":"foobar","healthCheck":{"scheme":"foobar","mode":"foobar","path":"foobar","method":"foobar","status":42,"port":42,"interval":"42s","unhealthyInterval":"42s","timeout":"42s","hostname":"foobar","followRedirects":true,"headers":{"name0":"foobar","name1":"foobar"}},"passiveHealthCheck":{"failureWindow":"42s","maxFailedAttempts":42},"passHostHeader":true,"responseForwarding":{"flushInterval":"42s"},"serversTransport":"foobar"}}}'
curl -X POST "$BASE_URL/http/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Service04","config":{"mirroring":{"service":"foobar","mirrorBody":true,"maxBodySize":42,"mirrors":[{"name":"foobar","percent":42},{"name":"foobar","percent":42}],"healthCheck":{}}}}'
curl -X POST "$BASE_URL/http/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Service05","config":{"weighted":{"services":[{"name":"foobar","weight":42},{"name":"foobar","weight":42}],"sticky":{"cookie":{"name":"foobar","secure":true,"httpOnly":true,"sameSite":"foobar","maxAge":42,"path":"foobar","domain":"foobar"}},"healthCheck":{}}}}'

echo "Creating HTTP Middlewares..."
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware01","config":{"addPrefix":{"prefix":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware02","config":{"basicAuth":{"users":["foobar","foobar"],"usersFile":"foobar","realm":"foobar","removeHeader":true,"headerField":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware03","config":{"buffering":{"maxRequestBodyBytes":42,"memRequestBodyBytes":42,"maxResponseBodyBytes":42,"memResponseBodyBytes":42,"retryExpression":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware04","config":{"chain":{"middlewares":["foobar","foobar"]}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware05","config":{"circuitBreaker":{"expression":"foobar","checkPeriod":"42s","fallbackDuration":"42s","recoveryDuration":"42s","responseCode":42}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware06","config":{"compress":{"excludedContentTypes":["foobar","foobar"],"includedContentTypes":["foobar","foobar"],"minResponseBodyBytes":42,"encodings":["foobar","foobar"],"defaultEncoding":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware07","config":{"contentType":{"autoDetect":true}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware08","config":{"digestAuth":{"users":["foobar","foobar"],"usersFile":"foobar","removeHeader":true,"realm":"foobar","headerField":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware09","config":{"errors":{"status":["foobar","foobar"],"statusRewrites":{"name0":42,"name1":42},"service":"foobar","query":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware10","config":{"forwardAuth":{"address":"foobar","tls":{"ca":"foobar","cert":"foobar","key":"foobar","insecureSkipVerify":true,"caOptional":true},"trustForwardHeader":true,"authResponseHeaders":["foobar","foobar"],"authResponseHeadersRegex":"foobar","authRequestHeaders":["foobar","foobar"],"addAuthCookiesToResponse":["foobar","foobar"],"headerField":"foobar","forwardBody":true,"maxBodySize":42,"preserveLocationHeader":true,"preserveRequestMethod":true}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware11","config":{"grpcWeb":{"allowOrigins":["foobar","foobar"]}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware12","config":{"headers":{"customRequestHeaders":{"name0":"foobar","name1":"foobar"},"customResponseHeaders":{"name0":"foobar","name1":"foobar"},"accessControlAllowCredentials":true,"accessControlAllowHeaders":["foobar","foobar"],"accessControlAllowMethods":["foobar","foobar"],"accessControlAllowOriginList":["foobar","foobar"],"accessControlAllowOriginListRegex":["foobar","foobar"],"accessControlExposeHeaders":["foobar","foobar"],"accessControlMaxAge":42,"addVaryHeader":true,"allowedHosts":["foobar","foobar"],"hostsProxyHeaders":["foobar","foobar"],"sslProxyHeaders":{"name0":"foobar","name1":"foobar"},"stsSeconds":42,"stsIncludeSubdomains":true,"stsPreload":true,"forceSTSHeader":true,"frameDeny":true,"customFrameOptionsValue":"foobar","contentTypeNosniff":true,"browserXssFilter":true,"customBrowserXSSValue":"foobar","contentSecurityPolicy":"foobar","contentSecurityPolicyReportOnly":"foobar","publicKey":"foobar","referrerPolicy":"foobar","permissionsPolicy":"foobar","isDevelopment":true,"featurePolicy":"foobar","sslRedirect":true,"sslTemporaryRedirect":true,"sslHost":"foobar","sslForceHost":true}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware13","config":{"ipAllowList":{"sourceRange":["foobar","foobar"],"ipStrategy":{"depth":42,"excludedIPs":["foobar","foobar"],"ipv6Subnet":42},"rejectStatusCode":42}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware14","config":{"ipWhiteList":{"sourceRange":["foobar","foobar"],"ipStrategy":{"depth":42,"excludedIPs":["foobar","foobar"],"ipv6Subnet":42}}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware15","config":{"inFlightReq":{"amount":42,"sourceCriterion":{"ipStrategy":{"depth":42,"excludedIPs":["foobar","foobar"],"ipv6Subnet":42},"requestHeaderName":"foobar","requestHost":true}}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware16","config":{"passTLSClientCert":{"pem":true,"info":{"notAfter":true,"notBefore":true,"sans":true,"serialNumber":true,"subject":{"country":true,"province":true,"locality":true,"organization":true,"organizationalUnit":true,"commonName":true,"serialNumber":true,"domainComponent":true},"issuer":{"country":true,"province":true,"locality":true,"organization":true,"commonName":true,"serialNumber":true,"domainComponent":true}}}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware17","config":{"plugin":{"PluginConf0":{"name0":"foobar","name1":"foobar"},"PluginConf1":{"name0":"foobar","name1":"foobar"}}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware18","config":{"rateLimit":{"average":42,"period":"42s","burst":42,"sourceCriterion":{"ipStrategy":{"depth":42,"excludedIPs":["foobar","foobar"],"ipv6Subnet":42},"requestHeaderName":"foobar","requestHost":true},"redis":{"endpoints":["foobar","foobar"],"tls":{"ca":"foobar","cert":"foobar","key":"foobar","insecureSkipVerify":true},"username":"foobar","password":"foobar","db":42,"poolSize":42,"minIdleConns":42,"maxActiveConns":42,"readTimeout":"42s","writeTimeout":"42s","dialTimeout":"42s"}}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware19","config":{"redirectRegex":{"regex":"foobar","replacement":"foobar","permanent":true}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware20","config":{"redirectScheme":{"scheme":"foobar","port":"foobar","permanent":true}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware21","config":{"replacePath":{"path":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware22","config":{"replacePathRegex":{"regex":"foobar","replacement":"foobar"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware23","config":{"retry":{"attempts":42,"initialInterval":"42s"}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware24","config":{"stripPrefix":{"prefixes":["foobar","foobar"],"forceSlash":true}}}'
curl -X POST "$BASE_URL/http/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Middleware25","config":{"stripPrefixRegex":{"regex":["foobar","foobar"]}}}'

echo "Creating HTTP ServersTransports..."
curl -X POST "$BASE_URL/http/serversTransport" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"ServersTransport0","config":{"serverName":"foobar","insecureSkipVerify":true,"rootCAs":["foobar","foobar"],"certificates":[{"certFile":"foobar","keyFile":"foobar"},{"certFile":"foobar","keyFile":"foobar"}],"maxIdleConnsPerHost":42,"forwardingTimeouts":{"dialTimeout":"42s","responseHeaderTimeout":"42s","idleConnTimeout":"42s","readIdleTimeout":"42s","pingTimeout":"42s"},"disableHTTP2":true,"peerCertURI":"foobar","spiffe":{"ids":["foobar","foobar"],"trustDomain":"foobar"}}}'
curl -X POST "$BASE_URL/http/serversTransport" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"ServersTransport1","config":{"serverName":"foobar","insecureSkipVerify":true,"rootCAs":["foobar","foobar"],"certificates":[{"certFile":"foobar","keyFile":"foobar"},{"certFile":"foobar","keyFile":"foobar"}],"maxIdleConnsPerHost":42,"forwardingTimeouts":{"dialTimeout":"42s","responseHeaderTimeout":"42s","idleConnTimeout":"42s","readIdleTimeout":"42s","pingTimeout":"42s"},"disableHTTP2":true,"peerCertURI":"foobar","spiffe":{"ids":["foobar","foobar"],"trustDomain":"foobar"}}}'

echo "Creating TCP Routers..."
curl -X POST "$BASE_URL/tcp/routers" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPRouter0","config":{"entryPoints":["foobar","foobar"],"middlewares":["foobar","foobar"],"service":"foobar","rule":"foobar","ruleSyntax":"foobar","priority":42,"tls":{"passthrough":true,"options":"foobar","certResolver":"foobar","domains":[{"main":"foobar","sans":["foobar","foobar"]},{"main":"foobar","sans":["foobar","foobar"]}]}}}'
curl -X POST "$BASE_URL/tcp/routers" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPRouter1","config":{"entryPoints":["foobar","foobar"],"middlewares":["foobar","foobar"],"service":"foobar","rule":"foobar","ruleSyntax":"foobar","priority":42,"tls":{"passthrough":true,"options":"foobar","certResolver":"foobar","domains":[{"main":"foobar","sans":["foobar","foobar"]},{"main":"foobar","sans":["foobar","foobar"]}]}}}'

echo "Creating TCP Services..."
curl -X POST "$BASE_URL/tcp/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPService01","config":{"loadBalancer":{"servers":[{"address":"foobar","tls":true},{"address":"foobar","tls":true}],"serversTransport":"foobar","proxyProtocol":{"version":42},"terminationDelay":42,"healthCheck":{"port":42,"send":"foobar","expect":"foobar","interval":"42s","unhealthyInterval":"42s","timeout":"42s"}}}}'
curl -X POST "$BASE_URL/tcp/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPService02","config":{"weighted":{"services":[{"name":"foobar","weight":42},{"name":"foobar","weight":42}],"healthCheck":{}}}}'

echo "Creating TCP Middlewares..."
curl -X POST "$BASE_URL/tcp/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPMiddleware01","config":{"ipAllowList":{"sourceRange":["foobar","foobar"]}}}'
curl -X POST "$BASE_URL/tcp/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPMiddleware02","config":{"ipWhiteList":{"sourceRange":["foobar","foobar"]}}}'
curl -X POST "$BASE_URL/tcp/middlewares" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPMiddleware03","config":{"inFlightConn":{"amount":42}}}'

echo "Creating TCP ServersTransports..."
curl -X POST "$BASE_URL/tcp/serversTransport" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPServersTransport0","config":{"dialKeepAlive":"42s","dialTimeout":"42s","proxyProtocol":{"version":42},"terminationDelay":"42s","tls":{"serverName":"foobar","insecureSkipVerify":true,"rootCAs":["foobar","foobar"],"certificates":[{"certFile":"foobar","keyFile":"foobar"},{"certFile":"foobar","keyFile":"foobar"}],"peerCertURI":"foobar","spiffe":{"ids":["foobar","foobar"],"trustDomain":"foobar"}}}}'
curl -X POST "$BASE_URL/tcp/serversTransport" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"TCPServersTransport1","config":{"dialKeepAlive":"42s","dialTimeout":"42s","proxyProtocol":{"version":42},"terminationDelay":"42s","tls":{"serverName":"foobar","insecureSkipVerify":true,"rootCAs":["foobar","foobar"],"certificates":[{"certFile":"foobar","keyFile":"foobar"},{"certFile":"foobar","keyFile":"foobar"}],"peerCertURI":"foobar","spiffe":{"ids":["foobar","foobar"],"trustDomain":"foobar"}}}}'

echo "Creating UDP Routers..."
curl -X POST "$BASE_URL/udp/routers" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"UDPRouter0","config":{"entryPoints":["foobar","foobar"],"service":"foobar"}}'
curl -X POST "$BASE_URL/udp/routers" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"UDPRouter1","config":{"entryPoints":["foobar","foobar"],"service":"foobar"}}'

echo "Creating UDP Services..."
curl -X POST "$BASE_URL/udp/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"UDPService01","config":{"loadBalancer":{"servers":[{"address":"foobar"},{"address":"foobar"}]}}}'
curl -X POST "$BASE_URL/udp/services" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"UDPService02","config":{"weighted":{"services":[{"name":"foobar","weight":42},{"name":"foobar","weight":42}]}}}'

echo "Creating HTTP TLS Options..."
curl -X POST "$BASE_URL/http/tls" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Options0","config":{"minVersion":"foobar","maxVersion":"foobar","cipherSuites":["foobar","foobar"],"curvePreferences":["foobar","foobar"],"clientAuth":{"caFiles":["foobar","foobar"],"clientAuthType":"foobar"},"sniStrict":true,"alpnProtocols":["foobar","foobar"],"disableSessionTickets":true,"preferServerCipherSuites":true}}'
curl -X POST "$BASE_URL/http/tls" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Options1","config":{"minVersion":"foobar","maxVersion":"foobar","cipherSuites":["foobar","foobar"],"curvePreferences":["foobar","foobar"],"clientAuth":{"caFiles":["foobar","foobar"],"clientAuthType":"foobar"},"sniStrict":true,"alpnProtocols":["foobar","foobar"],"disableSessionTickets":true,"preferServerCipherSuites":true}}'

echo "Creating TCP TLS Options..."
curl -X POST "$BASE_URL/tcp/tls" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Store0","config":{"defaultCertificate":{"certFile":"foobar","keyFile":"foobar"},"defaultGeneratedCert":{"resolver":"foobar","domain":{"main":"foobar","sans":["foobar","foobar"]}}}}'
curl -X POST "$BASE_URL/tcp/tls" -H "x-traefikr-key: $API_KEY" -H "Content-Type: application/json" -d '{"name":"Store1","config":{"defaultCertificate":{"certFile":"foobar","keyFile":"foobar"},"defaultGeneratedCert":{"resolver":"foobar","domain":{"main":"foobar","sans":["foobar","foobar"]}}}}'

echo ""
echo "All resources created successfully!"
